name: Rust

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  content:
    name: Content
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - uses: dtolnay/rust-toolchain@stable

    - name: Validate content
      run: cargo run --locked -- --check-content assets

  check:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy

    - name: Check
      run: cargo check --locked --all-targets --all-features --verbose

    - name: Format
      run: cargo fmt --check

    - name: Clippy
      run: cargo clippy --locked --all-targets --all-features -- -D warnings

    - name: Test
      run: cargo test --locked --verbose
